-- Add Orion and Beverly models
-- These should be displayed first (display_order: 0 and 1)

INSERT INTO public.models (
  slug,
  name_tr,
  name_en,
  tagline_tr,
  tagline_en,
  description_tr,
  description_en,
  size_sqm,
  bedrooms,
  bathrooms,
  price,
  is_popular,
  is_visible,
  display_order,
  main_image,
  features_tr,
  features_en,
  seo_title_tr,
  seo_title_en,
  seo_description_tr,
  seo_description_en
) VALUES
(
  'orion',
  'Orion',
  'Orion',
  'Tek Loftlu Kompakt Yaşam',
  'Single Loft Compact Living',
  'Orion modeli, 8-9 metre uzunluğunda ve 2.5 metre genişliğinde kompakt bir tiny house tasarımıdır. Tek loft yapısı ile maksimum alan kullanımı sağlar. Modern ve minimal tasarımı ile şehir hayatına uygun, taşınabilir bir yaşam alanı sunar.',
  'The Orion model is a compact tiny house design measuring 8-9 meters in length and 2.5 meters in width. With its single loft structure, it provides maximum space utilization. Its modern and minimal design offers a portable living space suitable for city life.',
  20,
  2,
  1,
  450000.00,
  true,
  true,
  0,
  '/orion-main.jpg',
  '["Tek Loft Yatak Odası", "Modern Mutfak", "Kompakt Banyo", "Geniş Oturma Alanı", "Enerji Verimli İzolasyon", "Taşınabilir Tasarım"]'::jsonb,
  '["Single Loft Bedroom", "Modern Kitchen", "Compact Bathroom", "Spacious Living Area", "Energy Efficient Insulation", "Portable Design"]'::jsonb,
  'Orion Tiny House | 2+1 Tek Loftlu Model | Moortinyhouse',
  'Orion Tiny House | 2+1 Single Loft Model | Moortinyhouse',
  'Orion modeli: 8-9 metre uzunluğunda, 2.5 metre genişliğinde tek loftlu tiny house. İstanbul ve Bursa''da kompakt yaşam çözümleri.',
  'Orion model: 8-9 meters long, 2.5 meters wide single loft tiny house. Compact living solutions in Istanbul and Bursa.'
),
(
  'beverly',
  'Beverly',
  'Beverly',
  'Aile İçin Geniş Yaşam Alanı',
  'Spacious Living Space for Families',
  'Beverly modeli, 3+1 oda düzenine sahip geniş bir tiny house tasarımıdır. 2.5 metre genişliğinde olmasına rağmen, akıllı tasarım sayesinde aileler için rahat bir yaşam alanı sunar. Çocuklu aileler için ideal olan bu model, her detayı düşünülmüş bir yaşam deneyimi sağlar.',
  'The Beverly model is a spacious tiny house design with a 3+1 room layout. Despite being 2.5 meters wide, it offers a comfortable living space for families thanks to its smart design. Ideal for families with children, this model provides a well-thought-out living experience.',
  35,
  3,
  1,
  650000.00,
  true,
  true,
  1,
  '/beverly-main.jpg',
  '["3 Yatak Odası", "Geniş Oturma Alanı", "Tam Donanımlı Mutfak", "Modern Banyo", "Çocuk Odası İçin Alan", "Depolama Çözümleri"]'::jsonb,
  '["3 Bedrooms", "Spacious Living Area", "Fully Equipped Kitchen", "Modern Bathroom", "Space for Children''s Room", "Storage Solutions"]'::jsonb,
  'Beverly Tiny House | 3+1 Aile Modeli | Moortinyhouse',
  'Beverly Tiny House | 3+1 Family Model | Moortinyhouse',
  'Beverly modeli: 3+1 oda düzenine sahip aile için geniş tiny house. İstanbul ve Bursa''da aile yaşamı için ideal çözüm.',
  'Beverly model: Spacious tiny house with 3+1 room layout for families. Ideal solution for family living in Istanbul and Bursa.'
)
ON CONFLICT (slug) DO UPDATE SET
  display_order = EXCLUDED.display_order,
  is_popular = EXCLUDED.is_popular,
  is_visible = EXCLUDED.is_visible;
